query myLists {
  myLists {
    id
    name
    items {
      id
      name
      done
    }
  }
}

mutation createList($name: String!) {
  createList(name: $name) {
    id
    name
    items {
      name
      id
      done
    }
  }
}
